# Generated by Django 3.2.8 on 2022-06-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('Record_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
                ('Power_Consumption', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-Date_Time'],
            },
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('appliance_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('appliance_Name', models.TextField(default='Unknown')),
                ('mean', models.FloatField(default=0)),
                ('std', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Mean', models.FloatField(default=0)),
                ('Std', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('Prediction_ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('prediction', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=0)),
                ('aggregate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predictionapp.aggregate')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predictionapp.appliance')),
            ],
            options={
                'ordering': ['appliance'],
            },
        ),
        migrations.AddField(
            model_name='appliance',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predictionapp.house'),
        ),
        migrations.AddField(
            model_name='aggregate',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Predictionapp.house'),
        ),
        migrations.AddIndex(
            model_name='predictions',
            index=models.Index(fields=['aggregate'], name='Predictiona_aggrega_e46a79_idx'),
        ),
        migrations.AddIndex(
            model_name='predictions',
            index=models.Index(fields=['appliance'], name='Predictiona_applian_ed6dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='predictions',
            index=models.Index(fields=['aggregate', 'appliance'], name='Predictiona_aggrega_33817e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='predictions',
            unique_together={('aggregate', 'appliance')},
        ),
        migrations.AddIndex(
            model_name='appliance',
            index=models.Index(fields=['house'], name='Predictiona_house_i_965839_idx'),
        ),
        migrations.AddIndex(
            model_name='appliance',
            index=models.Index(fields=['house', 'appliance_Name'], name='Predictiona_house_i_7bdc88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appliance',
            unique_together={('appliance_ID', 'house')},
        ),
        migrations.AddIndex(
            model_name='aggregate',
            index=models.Index(fields=['house'], name='Predictiona_house_i_41b741_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregate',
            index=models.Index(fields=['house', 'Date_Time'], name='Predictiona_house_i_8d7f95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregate',
            unique_together={('house', 'Date_Time')},
        ),
    ]
