# Generated by Django 3.2.8 on 2022-06-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predictionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='middle_layers_activation',
            field=models.TextField(default='relu'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='power_on_z_score',
            field=models.FloatField(default=0),
        ),
    ]
